-- =====================================================
-- SEED: Templates de Termos (HTML)
-- Data: 2026-07-11
CREATE TABLE IF NOT EXISTS termos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  titulo TEXT NOT NULL,
  conteudo_html TEXT NOT NULL,
  ativo INTEGER NOT NULL DEFAULT 1,
  created_by INTEGER,
  updated_by INTEGER,
  created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
  FOREIGN KEY (created_by) REFERENCES usuarios(id),
  FOREIGN KEY (updated_by) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_termos_ativo ON termos (ativo);
CREATE INDEX IF NOT EXISTS idx_termos_titulo ON termos (titulo);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'aparelho-montagem',
  'Termo de Consentimento - Montagem e manutenção de aparelho ortodôntico',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>MONTAGEM E MANUTENÇÃO DE APARELHO ORTODÔNTICO</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, autorizo a montagem e realização de manutenções do aparelho ortodôntico, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que o tratamento ortodôntico é um processo gradual e contínuo, cujos resultados dependem da cooperação do paciente, do comparecimento regular às consultas de manutenção e do cumprimento das orientações fornecidas pelo cirurgião-dentista. O não cumprimento das etapas e prazos pode comprometer o resultado final e prolongar o tempo de tratamento.</p>
<p>Estou ciente das condições de manutenção, conserto e demais regras aplicáveis ao meu tratamento ortodôntico, conforme descritas abaixo, e declaro ter compreendido e concordado com todas elas antes de assinar este termo.</p>
<p>DOS CONSERTOS E PEÇAS QUEBRADAS: Consertos poderão ser realizados sem custo adicional em até 24 horas após a data da manutenção. Para pacientes que realizam manutenção no valor de R$ 50,00 (Manutenção Convencional) ou R$ 70,00 (Manutenção Premium), será cobrado o valor de R$ 5,00 por peça quebrada do aparelho convencional, quando o conserto for solicitado em até 7 dias após a manutenção. Após os 7 dias da manutenção, será cortado apenas o fio, e o conserto das peças quebradas ocorrerá somente no dia da próxima manutenção, com custo adicional de R$ 5,00 por peça. Para pacientes que realizam manutenção no valor de R$ 80,00 (Manutenção Estética), após os 7 dias da manutenção, será cortado apenas o fio, e o conserto ocorrerá no dia da manutenção, com custo adicional de R$ 15,00 por peça quebrada. Para pacientes que realizam manutenção no valor de R$ 210,00 (Manutenção Autoligado), após os 7 dias da manutenção, será cortado apenas o fio, e o conserto ocorrerá no dia da manutenção, com custo adicional de R$ 20,00 por peça quebrada.</p>
<p>DA TROCA DE LIGAS: A troca de ligas poderá ser realizada em até 7 dias após a data da manutenção, mediante pagamento de R$ 10,00.</p>
<p>DA TROCA DO TIPO DE MANUTENÇÃO: Ao optar pela troca da Manutenção Premium pela Manutenção Convencional, o paciente perderá automaticamente todos os benefícios associados às manutenções Premium, sem direito a ressarcimento ou compensação pelos valores anteriormente pagos.</p>
<p>DA REMOÇÃO DO APARELHO: A remoção do aparelho ortodôntico será cobrada no valor de R$ 25,00 por arcada dentária. O paciente que optar pela remoção antes do término do tratamento perderá todos os benefícios a que teria direito ao concluir o tratamento, incluindo eventuais procedimentos inclusos no plano contratado, sem direito a qualquer restituição proporcional.</p>
<p>DO CLAREAMENTO DENTAL: O clareamento dental, quando incluso no plano de Manutenção Premium, somente poderá ser realizado após a conclusão do tratamento ortodôntico e a instalação dos aparelhos de contenção. O paciente só terá direito ao clareamento após o pagamento de 12 (doze) manutenções consecutivas, sem interrupção.</p>
<p>DA CONTENÇÃO: Ao final do tratamento ortodôntico, é obrigatória a confecção e instalação do aparelho de contenção, dispositivo indispensável para evitar a recidiva ou regressão dos resultados obtidos. A contenção possui custo adicional, que será informado pelo profissional responsável no momento da alta do tratamento.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>Declaro expressamente que as informações por mim prestadas ao profissional são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias e doenças preexistentes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão dos custos de montagem, materiais e serviços laboratoriais já incorridos desde o início do tratamento, fica estabelecido que, em caso de desistência após a instalação do aparelho, será retido o valor correspondente aos custos já suportados pela clínica. O pedido de estorno integral não será cabível nessa hipótese, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente incorridos.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta de manutenção realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos. O retorno após esse prazo poderá implicar novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'canal',
  'Termo de Consentimento para tratamento endodôntico (canal radicular)',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>TRATAMENTO ENDODÔNTICO (CANAL RADICULAR)</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, autorizo ser submetido(a) ao tratamento endodôntico (canal radicular) do elemento dentário nº {{elemento_dentario_num}}, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b.</p>
<p>Declaro ter sido informado que o tratamento/retratamento de canal radicular é um procedimento que visa conservar um dente que, de outro modo, teria que ser extraído. O procedimento consiste na remoção da polpa dental infectada ou necrosada, na desinfecção e modelagem dos canais radiculares e no preenchimento com material biocompatível, com a finalidade de eliminar a infecção e preservar o elemento dentário.</p>
<p>Embora este procedimento apresente alto índice de sucesso clínico, trata-se de um processo biológico, sujeito a variáveis individuais que podem influenciar o resultado, tais como: condição imunológica do paciente, anatomia radicular particular de cada dente, extensão e grau da infecção e espécies bacterianas envolvidas.</p>
<p>Fui informado de que o tratamento poderá, ocasionalmente, não atingir o resultado esperado, sendo possível a necessidade de retratamento endodôntico, cirurgia periapical (que consiste na raspagem e remoção da porção terminal da raiz, com preenchimento do canal com material biologicamente compatível) ou, em casos extremos, extração do elemento dentário.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: dor e sensibilidade pós-operatória, fratura de instrumento endodôntico no interior do canal, perfuração radicular, reação inflamatória transitória, falha no selamento apical e possibilidade de insucesso que demande nova intervenção.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>Declaro expressamente que as informações por mim prestadas ao profissional são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias, doenças preexistentes e hábitos relevantes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional por eventuais intercorrências.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Declaro que fui informado sobre a necessidade de realização de exames radiográficos complementares e que autorizo a execução dos mesmos, compreendendo que são imprescindíveis para o diagnóstico, planejamento e acompanhamento do tratamento, obedecendo ao princípio ALARA (As Low As Reasonably Achievable) de proteção radiológica.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 3 (três) meses para restaurações dentárias, contados a partir da data de realização do procedimento, desde que o paciente mantenha higiene bucal adequada, compareça às consultas de acompanhamento e siga as orientações fornecidas. A garantia não abrangerá situações decorrentes de mau uso, negligência, hábitos prejudiciais ou descumprimento das orientações do profissional.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento, fica estabelecido que, em caso de desistência após o início do tratamento ou após a encomenda de material laboratorial, será retido o valor correspondente aos custos já incorridos, incluindo materiais adquiridos, serviços laboratoriais e consultas realizadas. O paciente declara estar ciente de que o pedido de estorno integral não será cabível nessas hipóteses, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'devolucao',
  'Requerimento para devolução de valores',
  '<p>REQUERIMENTO PARA DEVOLUÇÃO DE VALORES</p>
<p>CLÍNICA SORRIA LESTE</p>
<p>Eu, {{cliente_nome}}, portador(a) do CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, solicito a devolução do valor de R$ {{valor_devolucao}} ({{valor_devolucao_extenso}}), pago em {{data_pagamento_origem}}, na Clínica Sorria Leste, localizada na Avenida Presidente Castelo Branco nº 5185 B, Barra do Ceará, Fortaleza/CE, em virtude de:</p>
<p>{{motivo_devolucao}}</p>
<p>Estou ciente de que este requerimento será analisado em prazo de até 5 (cinco) dias úteis, e que seu deferimento ficará condicionado à conformidade com as normas do Código de Defesa do Consumidor (Lei nº 8.078/1990), bem como às políticas internas da clínica relativas a cancelamentos e desistências.</p>
<p>Declaro estar ciente de que, caso o estorno seja deferido, poderá ser realizado via transferência bancária para a conta abaixo indicada, em espécie, ou, tratando-se de pagamento realizado por cartão, a Clínica Sorria Leste avaliará a situação e, sendo validada a devolução, esta ficará condicionada, obrigatoriamente, à disponibilização dos dados do mesmo cartão utilizado na transação. Comprometo-me a manter meu telefone de contato atualizado para viabilizar eventual agendamento de recebimento em espécie.</p>
<p>Declaro ainda que fui informado sobre os motivos da necessidade de fornecimento de CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão mantidos em total sigilo, não sendo compartilhados com terceiros, salvo obrigação legal. Consinto livremente com o tratamento dos meus dados pessoais para os fins aqui descritos.</p>
<p>Declaro, por fim, que as informações prestadas neste requerimento são verdadeiras e que a assinatura aposta ao final é a mesma constante no documento de identidade. Anejo à presente solicitação: cópia do RG, ficha clínica do paciente e requerimento assinado pelo paciente e pelo sócio-administrador.</p>
<p>DADOS BANCÁRIOS PARA DEVOLUÇÃO:</p>
<p>Nome do Favorecido: {{nome_favorecido}}</p>
<p>CPF: {{cpf_favorecido}}    Banco: {{banco_nome}}    Agência: {{banco_agencia}}</p>
<p>Conta: {{conta_favorecido}}    ( ) Poupança    ( ) Corrente</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura do Requerente — deve coincidir com a assinatura no RG)</p>
<p>(Assinatura do Sócio-Administrador)</p>',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'extracao',
  'Termo de Consentimento para extração dentária',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>EXTRAÇÃO DENTÁRIA</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, Endereço {{cliente_endereco}}, autorizo ser submetido(a) ao procedimento de extração dentária, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que a extração dentária é a remoção cirúrgica de um dente, indicada em casos de elementos dentários severamente comprometidos por cárie, fratura, doença periodontal, infecção irresponsiva ao tratamento conservador, ou como parte de planejamento ortodôntico. O procedimento será realizado sob anestesia local e poderá envolver a remoção do dente por partes, com possível remoção de tecido ósseo e sutura da ferida cirúrgica.</p>
<p>Fui informado sobre as etapas do procedimento: avaliação clínica e radiográfica inicial; aplicação de anestesia local; realização da extração com possível remoção óssea; sutura, quando necessária; e orientações detalhadas para recuperação pós-operatória adequada.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: dor, inchaço, sangramento, infecção, alveolite (inflamação do alvéolo), parestesia (perda temporária ou prolongada de sensibilidade), comunicação bucosinusal, fratura de instrumento ou de raiz e necessidade de nova intervenção cirúrgica.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Fui orientado sobre os cuidados pós-operatórios, incluindo: manter gaze sobre o local da extração e trocá-la conforme orientação; evitar alimentos quentes e duros nas primeiras 24 horas; não escovar diretamente sobre a área no primeiro dia; tomar medicamentos conforme prescrição; evitar esforço físico por 48 horas; não fumar nem ingerir bebidas alcoólicas por 72 horas; e comparecer às consultas de acompanhamento para avaliação e retirada de pontos.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias, doenças preexistentes (cardiopatias, diabetes, problemas de coagulação), condição de gravidez ou lactação e uso de anticoagulantes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal.</p>
<p>Declaro que fui informado sobre a necessidade de realização de exames radiográficos complementares e que autorizo a execução dos mesmos, compreendendo que são imprescindíveis para o diagnóstico, planejamento e acompanhamento do tratamento, obedecendo ao princípio ALARA de proteção radiológica.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento, fica estabelecido que, em caso de desistência após o início do tratamento ou após a encomenda de material laboratorial, será retido o valor correspondente aos custos já incorridos, incluindo materiais adquiridos, serviços laboratoriais e consultas realizadas. O paciente declara estar ciente de que o pedido de estorno integral não será cabível nessas hipóteses, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'facetas',
  'Termo de Consentimento para faceta dentária em resina composta',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>FACETA DENTÁRIA EM RESINA COMPOSTA</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, autorizo a realização do procedimento de faceta dentária em resina composta no(s) elemento(s) dentário(s) nº {{elementos_dentarios}}, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que a faceta dentária em resina composta é um procedimento estético que compreende a reconstrução parcial ou total de um dente, com a finalidade de alterar cor, formato, textura, tamanho ou posicionamento, bem como para o fechamento de diastemas, correção de anomalias (como microdentes) e tratamento de sequelas de trauma. Fui expressamente esclarecido de que se trata de procedimento irreversível, e que não existem garantias absolutas de manutenção dos resultados por tempo indeterminado, dado o caráter biológico e individual de cada paciente.</p>
<p>Fui informado de que o sucesso do procedimento depende de múltiplos fatores, incluindo a resposta biológica individual, hábitos do paciente (como consumo de alimentos com pigmentos, tabagismo, bruxismo e hábitos de higiene), e que o material restaurador está sujeito a pigmentação progressiva ao longo do tempo, o que não constitui defeito técnico.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: sensibilidade dentária transitória ou prolongada, fratura ou lascamento da faceta, descoloração do material, necessidade de nova intervenção ao longo do tempo e, em casos onde a lesão subjacente é extensa, possibilidade de indicação de tratamento endodôntico.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 90 (noventa) dias contados da data de realização do procedimento, cobrindo caimento, fraturas e ajustes da faceta sem custo adicional ao paciente. A garantia não abrange a substituição por alteração de cor decorrente da pigmentação natural do material com o passar do tempo, nem situações decorrentes de mau uso, negligência, hábitos prejudiciais ou descumprimento das orientações pós-operatórias.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro ter discutido com o cirurgião-dentista minha história de saúde geral, inclusive doenças conhecidas, medicamentos em uso e alergias. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional por eventuais intercorrências.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos e dos serviços já realizados, fica estabelecido que, em caso de desistência após o início do tratamento, será retido o valor correspondente aos custos já incorridos, incluindo materiais, serviços laboratoriais e consultas realizadas. O pedido de estorno integral não será cabível nessa hipótese, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica, ressalvado o direito de arrependimento previsto no art. 49 do Código de Defesa do Consumidor (CDC), aplicável exclusivamente a contratações realizadas fora do estabelecimento comercial.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais, serviços e consultas realizadas. O retorno após esse prazo poderá implicar novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'implante',
  'Termo de Consentimento para instalação de implante osseointegrado',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>INSTALAÇÃO DE IMPLANTE OSSEOINTEGRADO</p>
<p>Por este instrumento de consentimento livre e esclarecido, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo(a) menor {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, autorizo a realização do procedimento de instalação de implante osseointegrado na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}, nos seguintes elementos:</p>
<p>Implantes (dentes): {{implante_elementos_dentes}}    Coroas sobre implantes: {{implante_coroas}}    Protocolo sobre implante: {{implante_protocolo}}</p>
<p>Declaro que a ficha de anamnese foi preenchida e por mim assinada, apresentando informações que correspondem à verdade dos fatos, especialmente no que diz respeito às minhas condições de saúde geral e bucal. Não omiti qualquer dado quanto a doenças preexistentes de meu conhecimento, nem quanto ao uso de medicamentos, controlados ou não. Estou ciente de que a omissão de dados sobre minha saúde geral e bucal e sobre o uso de medicamentos pode interferir negativamente no planejamento e andamento do tratamento, na resposta biológica do meu organismo à técnica empregada, podendo ocasionar danos irreversíveis à minha saúde bucal e geral, inclusive por reações a substâncias medicamentosas utilizadas durante o procedimento ou prescritas no transcorrer do tratamento, que podem dar causa a problemas cardíacos, alérgicos e até a morte.</p>
<p>Declaro que, considerando minha queixa principal e após avaliação clínica e de eventuais exames complementares, o(a) profissional me esclareceu sobre o diagnóstico e o planejamento de tratamento, com alternativas e informações claras sobre os objetivos e riscos do planejamento terapêutico escolhido, bem como sobre minha responsabilidade de colaborar e contribuir para o bom andamento do tratamento.</p>
<p>Fui informado de que o tratamento proposto será realizado aproximadamente em {{previsao_inicio}}, podendo, todavia, sofrer prorrogação ou alteração de prazo, em razão de eventual complexidade que o caso apresentar no decorrer do tratamento, da resposta biológica do meu organismo à técnica empregada, da minha assiduidade às consultas e do seguimento das orientações fornecidas pelo(a) profissional.</p>
<p>Declaro estar ciente de que devo comparecer pontualmente às sessões previamente agendadas, seguindo rigorosamente as prescrições, encaminhamentos a outros especialistas e demais orientações fornecidas pelo(a) profissional, sob pena de ser declarado interrompido o tratamento. Também é de minha responsabilidade informar ao(à) profissional qualquer alteração decorrente do tratamento realizado, insatisfações ou dúvidas sobre o tratamento em execução, mantendo meus dados cadastrais sempre atualizados.</p>
<p>Fui assegurado(a) de que apenas procedimentos permitidos e cientificamente comprovados serão empregados, e aceito que o(a) cirurgião-dentista escolha o tipo de implante mais adequado ao meu caso. Fui também informado(a) de que pode ser necessário alterar o planejamento inicial durante o procedimento cirúrgico e/ou protético, em função de condição óssea desfavorável ou proximidade com estruturas anatômicas. Estou ciente dos riscos de exposição acidental do seio maxilar e de injúria acidental ao nervo alveolar inferior, com consequente parestesia, nos casos em que a intervenção cirúrgica ocorra próxima a essas estruturas. Todas as minhas perguntas foram claramente respondidas e recebi explicação detalhada sobre o tratamento.</p>
<p>Declaro ter sido informado(a) de que não existem garantias absolutas de que os implantes e seus respectivos elementos protéticos se manterão estáveis durante toda a minha vida, e que o sucesso a longo prazo dependerá de manutenção regular e adequada. Em certos casos, uma parcela dos implantes pode ser perdida em decorrência de fatores como má qualidade óssea, infecções pós-operatórias ou higienização deficiente. Nessas situações, poderá ser instalado novo implante após o adequado reparo ósseo do local.</p>
<p>Havendo qualquer alteração de meu conhecimento quanto à minha saúde bucal ou geral, bem como o surgimento de dores nos elementos dentários ou outras dores orofaciais, é de minha responsabilidade manter contato com o(a) profissional, viabilizando a necessária avaliação do meio bucal e dos fatores que possam ter influenciado ou causado eventuais danos ou alterações, os quais podem dar origem a prejuízos diversos e até à perda dos implantes e do trabalho protético instalado.</p>
<p>Caso ocorra a perda de um ou mais implantes e a reposição seja essencial para a instalação dos elementos protéticos, concordo em arcar com os custos dos materiais empregados, cabendo ao(à) profissional a realização de nova cirurgia sem cobrança de novos honorários. Os custos do anestesista, caso eu deseje que o procedimento seja realizado sob sedação, serão de minha exclusiva responsabilidade.</p>
<p>Fui esclarecido(a) a respeito dos cuidados pós-tratamento que devo manter para preservar a durabilidade do serviço odontológico realizado nas etapas cirúrgica e protética. O trabalho protético foi realizado com o material acordado, conforme tamanho e cor dos elementos previamente aprovados por mim.</p>
<p>Estou ciente de que, assim como o trabalho protético, os elementos dentários naturais podem sofrer alterações e danos por questões naturais, por deficiência na higienização, doenças periodontais ou outras alterações bucais advindas de fatores biológicos ou externos, que não terão como fato causador o tratamento realizado.</p>
<p>Estou ciente de que os implantes serão instalados de maneira precisa, observando a técnica indicada ao caso, com a devida osseointegração. Reconheço que não há garantia de que os implantes permanecerão imutáveis quanto à osseointegração, situação que pode ser agravada pelo hábito de fumar e pela deficiência na higienização.</p>
<p>O trabalho protético sobre os implantes será instalado de forma adequada e adaptada, conforme prevê a técnica, a fim de resguardar as questões funcionais da reabilitação oral.</p>
<p>Declaro ter conhecimento de que ao término do tratamento deverei retornar para consultas de acompanhamento, de acordo com os critérios estabelecidos pelo(a) profissional, visando preservar e manter o tratamento realizado. Reconheço que não é possível garantir o tempo de durabilidade dos procedimentos odontológicos, pois tal avaliação observará as condições de minha saúde, eventuais alterações bucais, hábitos em geral, adequada higienização oral, além de outros fatores internos ou externos que podem afetar o serviço prestado. O(a) profissional não se eximirá de avaliar eventual dano ou prejuízo alegado, reparando-o, quando o caso, dentro dos limites de sua responsabilidade.</p>
<p>Entendo a importância da saúde bucal e me comprometo a seguir as orientações da equipe odontológica, assim como a retornar às consultas de orientação e acompanhamento programadas.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o(a) profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 6 (seis) meses para implantes osseointegrados e próteses sobre implantes, contados a partir da data de instalação definitiva do trabalho protético, desde que o paciente compareça às consultas de manutenção periódica, mantenha higiene bucal adequada e não apresente hábitos parafuncionais sem o uso de placa de proteção. Para procedimentos de restauração, a garantia é de 3 (três) meses. Nos termos do art. 26, inciso II, do Código de Defesa do Consumidor, fica estipulado o prazo de 90 (noventa) dias, a partir da finalização e entrega do tratamento em perfeitas condições, para a comunicação de eventual vício aparente do serviço. A garantia não abrangerá situações decorrentes de mau uso, negligência, perda de osseointegração por fatores sistêmicos, tabagismo, higienização deficiente ou descumprimento das orientações fornecidas pelo(a) profissional.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento de implantodontia, fica estabelecido que, em caso de desistência após o início da etapa cirúrgica ou após a encomenda de componentes protéticos ou laboratoriais, será retido o valor correspondente aos custos já incorridos, incluindo materiais, serviços laboratoriais e consultas realizadas. O pedido de estorno integral não será cabível nessa hipótese, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'plano-anual',
  'Termo de Plano de Tratamento Ortodôntico Anual',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>PLANO DE TRATAMENTO ORTODÔNTICO ANUAL</p>
<p>CLÍNICA SORRIA LESTE</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, autorizo e contrato o Plano de Tratamento Ortodôntico Anual da Clínica Sorria Leste — Clínica Odontológica Sorria Leste Ltda., CNPJ 46.261.849/0001-10, situada na Avenida Presidente Castelo Branco, nº 5185 B, Barra do Ceará, Fortaleza/CE, Representante Legal Alanna Regina Bezerra Nobre — sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que o Plano de Tratamento Ortodôntico Anual tem duração de 12 meses e inclui 12 manutenções ortodônticas mensais e limpezas dentárias. O paciente deverá comparecer mensalmente às consultas de manutenção. Faltas sem aviso prévio de 24 horas poderão implicar perda da consulta e reagendamento conforme disponibilidade da clínica.</p>
<p>Fui informado sobre as modalidades de tratamento disponíveis:</p>
<p>Manutenção Convencional: uso de braquetes metálicos tradicionais com ligaduras elásticas, sem custo adicional pelo aparelho.</p>
<p>Manutenção Premium: braquetes metálicos com ligaduras elásticas, limpeza mensal inclusa e clareamento dental ao final do tratamento, sem custo adicional pelo aparelho. O clareamento somente será realizado após a conclusão do tratamento e instalação dos aparelhos de contenção, condicionado ao pagamento de todas as manutenções de forma consecutiva.</p>
<p>Estou ciente dos meus direitos como paciente: receber as manutenções e limpezas regulares previstas no plano contratado e ser informado sobre o progresso do tratamento. Assumo as obrigações de seguir rigorosamente as orientações do cirurgião-dentista, manter higiene bucal adequada e comparecer pontualmente às consultas agendadas.</p>
<p>Declaro ter sido informado que ao final do tratamento ortodôntico é obrigatória a confecção e instalação do aparelho de contenção, dispositivo indispensável para prevenir a recidiva dos resultados obtidos. A contenção possui custo adicional, que será informado pelo profissional responsável no momento da alta do tratamento.</p>
<p>Estou ciente de que durante o tratamento poderão ocorrer situações imprevistas, sendo necessárias alterações no plano estabelecido. Poderá ser indicado o emprego de anestésico local, com os riscos inerentes: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>DAS CONDIÇÕES DE PAGAMENTO: O valor total do plano poderá ser pago à vista ou parcelado em até 12 vezes sem juros. Em caso de inadimplência, incidirão multa de 2% (dois por cento) e juros moratórios de 1% (um por cento) ao mês sobre o valor em aberto, nos termos do art. 406 do Código Civil.</p>
<p>DA MULTA POR DESISTÊNCIA: Em caso de desistência do plano contratado após o início do tratamento, incidirá multa rescisória de 30% (trinta por cento) sobre o valor total do plano. Não haverá devolução dos valores já pagos relativos a consultas e manutenções realizadas, ressalvado exclusivamente o direito de arrependimento previsto no art. 49 do Código de Defesa do Consumidor, aplicável a contratações realizadas fora do estabelecimento comercial no prazo de 7 dias.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias e doenças preexistentes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da LGPD (Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais, serviços e consultas realizadas. O retorno após esse prazo poderá implicar novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>Este termo é regido pelas normas do Código de Defesa do Consumidor (Lei nº 8.078/1990), Código Civil (Lei nº 10.406/2002), Código de Ética Odontológica e legislação pertinente. Fica eleito o foro da Comarca de Fortaleza, Estado do Ceará, para dirimir quaisquer controvérsias decorrentes do presente instrumento.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'plano-semestral',
  'Termo de Plano de Tratamento Ortodôntico Semestral',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>PLANO DE TRATAMENTO ORTODÔNTICO SEMESTRAL</p>
<p>CLÍNICA SORRIA LESTE</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, autorizo e contrato o Plano de Tratamento Ortodôntico Semestral da Clínica Sorria Leste — Clínica Odontológica Sorria Leste Ltda., CNPJ 46.261.849/0001-10, situada na Avenida Presidente Castelo Branco, nº 5185 B, Barra do Ceará, Fortaleza/CE, Representante Legal Alanna Regina Bezerra Nobre — sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que o Plano de Tratamento Ortodôntico Semestral tem duração de 6 meses e inclui 6 manutenções ortodônticas mensais e limpezas dentárias. O paciente deverá comparecer mensalmente às consultas de manutenção. Faltas sem aviso prévio de 24 horas poderão implicar perda da consulta e reagendamento conforme disponibilidade da clínica.</p>
<p>Fui informado sobre as modalidades de tratamento disponíveis:</p>
<p>Manutenção Convencional: uso de braquetes metálicos tradicionais com ligaduras elásticas, sem custo adicional pelo aparelho.</p>
<p>Manutenção Premium: braquetes metálicos com ligaduras elásticas, limpeza mensal inclusa e clareamento dental ao final do tratamento, sem custo adicional pelo aparelho. O clareamento somente será realizado após a conclusão do tratamento e instalação dos aparelhos de contenção, condicionado ao pagamento de todas as manutenções de forma consecutiva.</p>
<p>Estou ciente dos meus direitos como paciente: receber as manutenções e limpezas regulares previstas no plano contratado e ser informado sobre o progresso do tratamento. Assumo as obrigações de seguir rigorosamente as orientações do cirurgião-dentista, manter higiene bucal adequada e comparecer pontualmente às consultas agendadas.</p>
<p>Declaro ter sido informado que ao final do tratamento ortodôntico é obrigatória a confecção e instalação do aparelho de contenção, dispositivo indispensável para prevenir a recidiva dos resultados obtidos. A contenção possui custo adicional, que será informado pelo profissional responsável no momento da alta do tratamento.</p>
<p>Estou ciente de que durante o tratamento poderão ocorrer situações imprevistas, sendo necessárias alterações no plano estabelecido. Poderá ser indicado o emprego de anestésico local, com os riscos inerentes: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>DAS CONDIÇÕES DE PAGAMENTO: O valor total do plano poderá ser pago à vista ou parcelado em até 6 vezes sem juros. Em caso de inadimplência, incidirão multa de 2% (dois por cento) e juros moratórios de 1% (um por cento) ao mês sobre o valor em aberto, nos termos do art. 406 do Código Civil.</p>
<p>DA MULTA POR DESISTÊNCIA: Em caso de desistência do plano contratado após o início do tratamento, incidirá multa rescisória de 30% (trinta por cento) sobre o valor total do plano. Não haverá devolução dos valores já pagos relativos a consultas e manutenções realizadas, ressalvado exclusivamente o direito de arrependimento previsto no art. 49 do Código de Defesa do Consumidor, aplicável a contratações realizadas fora do estabelecimento comercial no prazo de 7 dias.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias e doenças preexistentes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da LGPD (Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais, serviços e consultas realizadas. O retorno após esse prazo poderá implicar novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>Este termo é regido pelas normas do Código de Defesa do Consumidor (Lei nº 8.078/1990), Código Civil (Lei nº 10.406/2002), Código de Ética Odontológica e legislação pertinente. Fica eleito o foro da Comarca de Fortaleza, Estado do Ceará, para dirimir quaisquer controvérsias decorrentes do presente instrumento.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'protese-com-extracao',
  'Termo de Confecção de Prótese com Extração Prévia',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>CONFECÇÃO DE PRÓTESE COM EXTRAÇÃO PRÉVIA</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, autorizo ser submetido(a) ao planejamento e confecção de prótese dentária com extração prévia, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que, na consulta inicial realizada em {{data_consulta_inicial}}, foram avaliados os elementos dentários e discutidas as opções de tratamento. Constatou-se a necessidade de extração de um ou mais dentes, sendo esclarecido que a confecção da prótese somente poderá ser iniciada após o período mínimo de cicatrização, estimado entre 30 e 90 dias a contar da data da extração, podendo esse prazo variar conforme a resposta biológica individual do paciente.</p>
<p>Fui informado sobre as opções de prótese disponíveis e realizei minha escolha conforme indicação clínica do cirurgião-dentista:</p>
<p>( ) Prótese Dentária Fixa (porcelana ou resina)    ( ) Coroa Dentária    ( ) Prótese Parcial Removível    ( ) Prótese Total    ( ) Prótese sobre Implante</p>
<p>Escolha do paciente: {{escolha_protese}}    Observações: {{observacoes_protese}}</p>
<p>Fui informado sobre as etapas do tratamento: 1ª) Extração e período de cicatrização (30 a 90 dias); 2ª) Moldagem para confecção da prótese; 3ª) Prova de cera para avaliação de estética e funcionalidade; 4ª) Prova final da peça protética; 5ª) Entrega da prótese; 6ª) Ajustes finais, caso necessários.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: afrouxamento ou fratura da prótese, necessidade de reembasamento ou substituição ao longo do tempo, reações gengivais ou ósseas, e, em casos excepcionais, impossibilidade de instalação da peça inicialmente planejada, com necessidade de novo planejamento.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas ao profissional são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias e doenças preexistentes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da LGPD (Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 6 (seis) meses para próteses, coroas e implantes, contados a partir da data de instalação definitiva, desde que o paciente compareça às consultas de manutenção periódica, mantenha higiene bucal adequada e não apresente hábitos parafuncionais sem o uso de placa de proteção. Para procedimentos de restauração, a garantia é de 3 (três) meses. A garantia não abrangerá situações decorrentes de mau uso, negligência, acidentes, alterações sistêmicas supervenientes ou descumprimento das orientações fornecidas pelo profissional.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento, fica estabelecido que, em caso de desistência após o início do tratamento ou após a encomenda de material laboratorial, será retido o valor correspondente aos custos já incorridos, incluindo materiais adquiridos, serviços laboratoriais e consultas realizadas. O paciente declara estar ciente de que o pedido de estorno integral não será cabível nessas hipóteses, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>TERMO DE RECEBIMENTO DA PRÓTESE</p>
<p>Eu, {{cliente_nome}}, CPF {{cliente_cpf}}, declaro que recebi a prótese conforme acordado com o cirurgião-dentista, que a peça atende às minhas expectativas quanto à estética e funcionalidade e que os ajustes necessários foram realizados. Estou ciente das condições de garantia acima descritas, da necessidade de manutenções periódicas e de que não haverá trocas ou reparos por questões estéticas ou decorrentes de uso inadequado.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável — recebimento da prótese)</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'protese-sem-extracao',
  'Termo de Confecção de Prótese sem Extração Prévia',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>CONFECÇÃO DE PRÓTESE SEM EXTRAÇÃO PRÉVIA</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, autorizo ser submetido(a) ao planejamento e confecção de prótese dentária, sem necessidade de extração prévia, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que, na consulta inicial realizada em {{data_consulta_inicial}}, foram avaliados os elementos dentários e discutidas as opções de tratamento. O paciente foi orientado sobre as características, limitações e cuidados inerentes a cada modalidade protética, e optou pela alternativa mais adequada conforme necessidade clínica e recomendação do cirurgião-dentista.</p>
<p>Fui informado sobre as opções de prótese disponíveis e realizei minha escolha conforme indicação clínica:</p>
<p>( ) Prótese Dentária Fixa (porcelana ou resina)    ( ) Coroa Dentária    ( ) Prótese Parcial Removível    ( ) Prótese Total    ( ) Prótese sobre Implante</p>
<p>Escolha do paciente: {{escolha_protese}}    Observações: {{observacoes_protese}}</p>
<p>Fui informado sobre as etapas do tratamento: 1ª) Moldagem e ajuste inicial (o paciente será convocado em até 15 dias após a consulta inicial, com sub-etapas de moldagem, prova de cera e prova com os dentes); 2ª) Prova de cera, com possibilidade de ajustes estéticos e funcionais; 3ª) Prova final para verificação de todos os aspectos estéticos e funcionais; 4ª) Entrega da prótese/coroa; 5ª) Ajustes posteriores, caso necessários.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: afrouxamento, fratura ou lascamento da prótese, necessidade de reembasamento ou substituição ao longo do tempo, reações gengivais e, em casos excepcionais, necessidade de extração de elemento dentário subjacente.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas ao profissional são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias e doenças preexistentes. Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da LGPD (Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 6 (seis) meses para próteses, coroas e implantes, contados a partir da data de instalação definitiva, desde que o paciente compareça às consultas de manutenção periódica, mantenha higiene bucal adequada e não apresente hábitos parafuncionais sem o uso de placa de proteção. Para procedimentos de restauração, a garantia é de 3 (três) meses. A garantia não abrangerá situações decorrentes de mau uso, negligência, acidentes, alterações sistêmicas supervenientes ou descumprimento das orientações fornecidas pelo profissional.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento, fica estabelecido que, em caso de desistência após o início do tratamento ou após a encomenda de material laboratorial, será retido o valor correspondente aos custos já incorridos, incluindo materiais adquiridos, serviços laboratoriais e consultas realizadas. O paciente declara estar ciente de que o pedido de estorno integral não será cabível nessas hipóteses, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>TERMO DE RECEBIMENTO DA PRÓTESE/COROA</p>
<p>Eu, {{cliente_nome}}, CPF {{cliente_cpf}}, declaro que recebi a prótese ou coroa conforme acordado com o cirurgião-dentista, que a peça atende às minhas expectativas quanto à estética e funcionalidade e que os ajustes necessários foram realizados. Estou ciente das condições de garantia acima descritas, da necessidade de manutenções periódicas e de que não haverá trocas ou reparos por questões estéticas ou decorrentes de uso inadequado.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável — recebimento da prótese)</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);

INSERT OR IGNORE INTO termos (slug, titulo, conteudo_html, ativo, created_by, updated_by) VALUES (
  'restauracao',
  'Termo de Consentimento para restauração dentária',
  '<p>TERMO DE CONSENTIMENTO INFORMADO</p>
<p>RESTAURAÇÃO DENTÁRIA</p>
<p>Por este instrumento, eu {{cliente_nome}}, na qualidade de paciente ou responsável legal (pai, mãe ou tutor) pelo paciente {{cliente_nome}}, CPF {{cliente_cpf}}, TELEFONE {{cliente_telefone}}, E-mail {{cliente_email}}, Endereço {{cliente_endereco}}, autorizo ser submetido(a) ao procedimento de restauração dentária, na Clínica Sorria Leste, situada na Avenida Presidente Castelo Branco, 5185 b, sob responsabilidade do(a) profissional {{profissional_nome}}, CRO {{profissional_cro}}.</p>
<p>Declaro ter sido informado que a restauração dentária é um procedimento que visa restabelecer a forma, função e estética de dentes comprometidos por cárie, fratura ou desgaste. O procedimento envolve as seguintes etapas: avaliação clínica e radiográfica; remoção do tecido cariado ou danificado; reconstrução com resina composta ou outro material adequado; e ajustes finais com polimento e verificação da oclusão.</p>
<p>Fui informado de que o sucesso da restauração depende de múltiplos fatores, incluindo: extensão da lesão, estrutura remanescente do dente, hábitos do paciente (bruxismo, consumo de alimentos com corantes, uso de substâncias abrasivas), higiene bucal e comparecimento às consultas de manutenção.</p>
<p>Estou ciente dos possíveis riscos e complicações inerentes ao procedimento, incluindo, mas não se limitando a: sensibilidade dentária transitória ou prolongada, fratura ou lascamento da restauração, descoloração do material com o tempo, cárie secundária na margem da restauração, necessidade de nova intervenção e, em casos onde a lesão atinge a polpa, possibilidade de indicação de tratamento endodôntico.</p>
<p>Estou ciente de que durante o procedimento poderão ocorrer situações não diagnosticadas neste momento ou imprevistas, sendo necessárias alterações no plano de tratamento. Poderá ser indicado o emprego de anestésico local, que apresenta os seguintes riscos: desmaio, dificuldade de respiração e reação alérgica. Além disso, poderão ocorrer desconforto, inchaço, equimose, infecção e dormência prolongada.</p>
<p>Admito os riscos mencionados e permito voluntariamente que sejam realizados os procedimentos necessários para tentar solucionar as situações imprevisíveis e/ou emergenciais que possam vir a ocorrer.</p>
<p>Fui orientado sobre os cuidados pós-operatórios, incluindo: manter higiene bucal adequada com escovação e uso de fio dental; evitar alimentos com corantes intensos, muito duros ou pegajosos; e comparecer obrigatoriamente às consultas de acompanhamento agendadas.</p>
<p>Tive a oportunidade de esclarecer todas as dúvidas e de compreender todas as informações constantes neste documento, antes de sua assinatura. Portanto, aceito e autorizo a execução do tratamento, comprometendo-me a seguir rigorosamente as orientações do cirurgião-dentista, comunicando imediatamente qualquer alteração em decorrência dos procedimentos realizados e comparecer pontualmente às consultas marcadas.</p>
<p>Declaro expressamente que as informações por mim prestadas ao profissional são verdadeiras e completas, incluindo dados sobre meu estado de saúde geral, medicamentos em uso, alergias, doenças preexistentes e pressão arterial (quando aplicável). Estou ciente de que a omissão ou falsidade de informações poderá comprometer o resultado do tratamento e afastar a responsabilidade da clínica e do profissional.</p>
<p>Reconheço que a obrigação do cirurgião-dentista é de meio e não de resultado, conforme entendimento consolidado do Conselho Federal de Odontologia e da jurisprudência pátria, o que significa que o profissional se compromete a empregar todos os recursos técnicos e científicos disponíveis para a obtenção do melhor resultado possível, sem, contudo, garantir resultado específico, dado o caráter biológico e individual de cada organismo.</p>
<p>Fui informado do motivo da necessidade de informar meu CPF e Telefone, nos termos da LGPD (Lei nº 13.709/2018), e que todos os meus dados serão utilizados exclusivamente para fins de atendimento clínico, ficando em total sigilo e não sendo compartilhados com terceiros, salvo obrigação legal. Declaro que consinto, de forma livre e esclarecida, com o tratamento dos meus dados pessoais pela Clínica Sorria Leste para as finalidades aqui descritas.</p>
<p>DA GARANTIA: A Clínica Sorria Leste oferece garantia de 3 (três) meses para restaurações dentárias, contados a partir da data de realização do procedimento, desde que o paciente mantenha higiene bucal adequada, compareça às consultas de acompanhamento e siga as orientações fornecidas. A garantia não abrangerá situações decorrentes de mau uso, negligência, hábitos prejudiciais ou descumprimento das orientações do profissional.</p>
<p>DA POLÍTICA DE CANCELAMENTO E ESTORNO: Em razão da aquisição de materiais específicos para a realização do procedimento, fica estabelecido que, em caso de desistência após o início do tratamento ou após a encomenda de material laboratorial, será retido o valor correspondente aos custos já incorridos, incluindo materiais adquiridos, serviços laboratoriais e consultas realizadas. O paciente declara estar ciente de que o pedido de estorno integral não será cabível nessas hipóteses, sendo devolvido apenas o valor eventualmente pago que exceder os custos efetivamente suportados pela clínica.</p>
<p>DA DESISTÊNCIA TÁCITA: Considera-se desistência tácita do tratamento a ausência injustificada do paciente por período igual ou superior a 90 (noventa) dias contados da última consulta realizada ou do último contato com a clínica, sem qualquer comunicação formal de suspensão ou reagendamento. Nessa hipótese, o tratamento será considerado encerrado por iniciativa do paciente, não sendo devida qualquer restituição de valores já pagos relativos a materiais adquiridos, serviços laboratoriais executados ou consultas realizadas. O retorno do paciente após esse prazo poderá implicar a necessidade de novo planejamento e novos custos.</p>
<p>Este termo tem caráter irrevogável e será arquivado no prontuário do paciente, constituindo documento hábil para todos os fins de direito, inclusive em eventuais processos administrativos perante o Conselho Regional de Odontologia (CRO) ou demandas judiciais e extrajudiciais.</p>
<p>TERMO DE RECEBIMENTO DA RESTAURAÇÃO</p>
<p>Eu, {{cliente_nome}}, CPF {{cliente_cpf}}, declaro que recebi a restauração conforme planejado, e que estou ciente das condições de garantia de 3 (três) meses para falhas técnicas, bem como da necessidade de manutenção periódica e seguimento das orientações pós-operatórias.</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável — recebimento da restauração)</p>
<p>___________________, _____ de _______________ de 20____.</p>
<p>(Assinatura e CPF do(a) paciente/responsável)</p>
<p>CONFIRMO que li o referido termo juntamente com o(a) paciente, e todas as suas dúvidas foram esclarecidas.</p>
',
  1,
  NULL,
  NULL
);
